/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export interface MoodCheckIn {
  date: string; // YYYY-MM-DD
  mood: 'calm' | 'anxious' | 'sad' | 'excited' | 'overwhelmed' | 'peaceful';
  note?: string;
}

export interface UserSession {
  id: string;
  username: string; // Anonymous username (e.g., "SereneOctopus")
  avatarSeed: string; // Seed/color identifier for UI avatar
  role: 'admin' | 'user';
  createdAt: string;
  streak: number;
  moodHistory: MoodCheckIn[];
  bookmarks: string[]; // Post IDs
}

export type ReactionType = 'support' | 'hugs' | 'metoo' | 'listen' | 'heart';

export interface ReactionDetail {
  emoji: string;
  label: string;
  color: string;
}

export const REACTION_MAP: Record<ReactionType, ReactionDetail> = {
  support: { emoji: '💜', label: 'Support', color: 'bg-indigo-500/15 text-indigo-400 hover:bg-indigo-500/25 border-indigo-500/30' },
  hugs: { emoji: '🫂', label: 'Hugs', color: 'bg-rose-500/15 text-rose-400 hover:bg-rose-500/25 border-rose-500/30' },
  metoo: { emoji: '👋', label: 'Me Too', color: 'bg-emerald-500/15 text-emerald-400 hover:bg-emerald-500/25 border-emerald-500/30' },
  listen: { emoji: '🎧', label: 'Listening', color: 'bg-amber-500/15 text-amber-400 hover:bg-amber-500/25 border-amber-500/30' },
  heart: { emoji: '❤️', label: 'Heart', color: 'bg-red-500/15 text-red-400 hover:bg-red-500/25 border-red-500/30' },
};

export interface Comment {
  id: string;
  postId: string;
  content: string;
  username: string;
  avatarSeed: string;
  createdAt: string;
}

export interface Post {
  id: string;
  title: string;
  content: string;
  category: string;
  imageUrl?: string;
  createdAt: string;
  username: string;
  avatarSeed: string;
  reactions: Record<ReactionType, number>;
  userReactions?: Record<string, ReactionType>; // userId -> reactionType
  isReported: boolean;
  reportsCount: number;
  reportReason?: string;
  aiModerated: boolean;
  aiSafetyStatus: 'clean' | 'flagged' | 'pending';
  aiReflection?: string; // Thoughtful response generated by Gemini
  comments: Comment[];
}

export const CATEGORIES = [
  'Confession',
  'Struggle',
  'Reflection',
  'Gratitude',
  'Dream',
  'Celebration'
] as const;

export interface APIResponse<T> {
  success: boolean;
  data?: T;
  error?: string;
}
